voter: xeroc
assets:
 - CNY

features:

 - description: "Require reliability during block production"
   block_production:
     max_misses: 2
   on_failure:
    - disapprove_witness
    - log
    - jekyll
   on_success: []

 - description: "Require reliability with CNY MCR"
   feed_mcr:
     assets:
      - CNY
     max: 175
     min: 175
   on_failure:
    - disapprove_witness
    - log
    - jekyll
   on_success: []

 - description: "Require reliability with CNY MSSR"
   feed_mssr:
     assets:
      - CNY
     max: 115
     min: 102
   on_failure:
    - disapprove_witness
    - log
    - jekyll
   on_success: []

 - description: "Require reliability feed publishing"
   feed_age:
     assets:
      - CNY
     max: 1m
   on_failure:
    - disapprove_witness
    - log
    - jekyll
   on_success: []

 - description: "Feed price"
   feed_settlementprice:
     assets:
      - CNY
     diff_percentage:
       max: 1.5
   on_failure:
    - disapprove_witness
    - log
    - jekyll
   on_success: []

actions:
 disapprove_witness:
  description: Disapprove failing witnesses
 log:
  description: Log Actions
 jekyll:
  dest: ../proxy.xeroc.org/_log
